import AppShell from "@/components/AppShell";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, CircleAlert, Eye, Package, Plus, ShoppingBag, Store, TrendingUp, Upload } from "lucide-react";
import { Link } from "wouter";

const brl = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default function Dashboard() {
  const { data, isLoading } = trpc.dashboard.overview.useQuery();
  if (isLoading || !data) return <AppShell><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-32 animate-pulse rounded-3xl bg-black/5" />)}</div></AppShell>;
  const { establishment, counts, recentOrders } = data;
  const checks = [{ label: "Estabelecimento criado", done: true }, { label: "Logo adicionada", done: Boolean(establishment.logoUrl) }, { label: "Modelo escolhido", done: true }, { label: "Categoria criada", done: counts.categories > 0 }, { label: "Primeiro produto criado", done: counts.products > 0 }, { label: "WhatsApp configurado", done: Boolean(establishment.whatsapp) }, { label: "Entrega configurada", done: true }, { label: "Cardápio publicado", done: Boolean(establishment.isPublished) }];
  const completion = Math.round((checks.filter(check=>check.done).length / checks.length) * 100);
  return <AppShell>
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-black/45">Bom dia, {establishment.name.split(" ")[0]} <span>✦</span></p><h1 className="display-serif mt-2 text-4xl sm:text-5xl">Seu negócio em movimento.</h1><p className="mt-3 text-sm text-black/50">Aqui está o resumo do seu cardápio hoje.</p></div><div className="flex gap-2"><Link href="/dashboard/modelos" className="button-pop inline-flex items-center rounded-full border border-black/10 bg-white px-4 py-3 text-sm font-bold"><PaletteIcon /> Personalizar</Link><Link href="/dashboard/produtos" className="button-pop inline-flex items-center rounded-full bg-[#ef6b4b] px-4 py-3 text-sm font-bold text-white shadow-lg shadow-[#ef6b4b]/15"><Plus className="mr-2 h-4 w-4" /> Novo produto</Link></div></div>
    {!establishment.isPublished && <div className="mt-8 flex flex-col justify-between gap-4 rounded-3xl bg-[#111315] p-5 text-white sm:flex-row sm:items-center sm:p-6"><div className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#ef6b4b]"><Upload className="h-5 w-5" /></span><div><p className="font-bold">Seu cardápio ainda não está online</p><p className="mt-1 text-sm text-white/50">Finalize os últimos ajustes e compartilhe com seus clientes.</p></div></div><Link href="/dashboard/cardapio" className="rounded-full bg-white px-4 py-2.5 text-center text-sm font-bold text-[#111315]">Publicar agora <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div>}
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{label:"Pedidos hoje", value:counts.orders, icon:ShoppingBag, change:"+12% vs. ontem", color:"#ef6b4b"},{label:"Faturamento", value:brl(counts.revenue), icon:TrendingUp, change:"Pedidos não cancelados", color:"#3d766a"},{label:"Produtos ativos", value:counts.products, icon:Package, change:"No seu cardápio", color:"#b58337"},{label:"Visualizações", value:establishment.views, icon:Eye, change:"Acessos ao cardápio", color:"#8d7bbd"}].map(card=>{const Icon=card.icon;return <div key={card.label} className="rounded-3xl bg-white p-5 soft-shadow"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl" style={{backgroundColor:`${card.color}18`, color:card.color}}><Icon className="h-5 w-5" /></span><span className="rounded-full bg-black/5 px-2 py-1 text-[10px] font-bold text-black/35">30 dias</span></div><p className="mt-7 text-sm text-black/45">{card.label}</p><p className="mt-1 text-2xl font-bold tracking-tight">{card.value}</p><p className="mt-2 text-xs text-black/35">{card.change}</p></div>})}</div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl bg-white p-6 soft-shadow"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Pedidos recentes</h2><p className="mt-1 text-sm text-black/45">Acompanhe o que está chegando agora.</p></div><Link href="/dashboard/pedidos" className="text-sm font-bold text-[#ef6b4b]">Ver todos <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div>{recentOrders.length ? <div className="mt-6 divide-y divide-black/6">{recentOrders.map(order=><div key={order.id} className="flex items-center justify-between gap-4 py-4"><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#f9e2db] text-xs font-bold text-[#d85139]">#{String(order.orderNumber).slice(-2)}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{order.customerName}</p><p className="mt-1 text-xs text-black/40">{order.fulfillmentType === "delivery" ? "Entrega" : "Retirada"} · {new Date(order.createdAt).toLocaleTimeString("pt-BR", {hour:"2-digit", minute:"2-digit"})}</p></div></div><div className="text-right"><p className="text-sm font-bold">{brl(order.total)}</p><span className="mt-1 inline-block rounded-full bg-[#e5f1ed] px-2 py-1 text-[10px] font-bold text-[#3d766a]">{order.status === "new" ? "Novo" : order.status}</span></div></div>)}</div> : <div className="mt-6 rounded-2xl bg-[#f6f4ef] p-8 text-center"><ShoppingBag className="mx-auto h-7 w-7 text-black/20" /><p className="mt-3 text-sm font-semibold">Seus pedidos aparecerão aqui</p><p className="mt-1 text-xs text-black/40">Publique o cardápio para começar a receber.</p></div>}</section>
      <section className="rounded-3xl bg-[#e8eee9] p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Seu progresso</h2><p className="mt-1 text-sm text-black/45">Deixe tudo pronto para vender.</p></div><span className="text-2xl font-bold text-[#3d766a]">{completion}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-black/8"><div className="h-full rounded-full bg-[#3d766a] transition-all" style={{width:`${completion}%`}} /></div><div className="mt-5 space-y-3">{checks.map(check=><div key={check.label} className="flex items-center gap-3 text-sm"><span className={`flex h-5 w-5 items-center justify-center rounded-full ${check.done?"bg-[#3d766a] text-white":"border border-black/15 text-transparent"}`}>{check.done?<Check className="h-3 w-3" />:<span className="h-1.5 w-1.5 rounded-full bg-black/15" />}</span><span className={check.done?"text-black/60":"text-black/45"}>{check.label}</span></div>)}</div><Link href="/dashboard/estabelecimento" className="mt-6 block rounded-full bg-white py-3 text-center text-sm font-bold text-[#315c53]">Completar cadastro <ArrowRight className="ml-1 inline h-4 w-4" /></Link></section></div>
  </AppShell>;
}
function PaletteIcon(){ return <span className="mr-2 text-base">✦</span>; }
